/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rudy Duarte, Albert Li 
 */
import javax.swing.*;
import java.util.*;
import java.awt.*;
import javax.swing.event.*;
import javax.swing.border.*;
import javax.swing.DefaultListModel;

public class GS_GUI extends javax.swing.JFrame {
    private final int boxPrice = 4;
    private int totalBoxes = 0;
    private double total = 0;
    private String totalBoxString = "Total Boxes: ";
    private String totalString = "Total: $";
    private int previousBox [] = new int [6];
    DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form 
     */
    public GS_GUI() {
        initComponents();
        searchResultList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        firstNameField = new javax.swing.JTextField();
        streetField = new javax.swing.JTextField();
        aptField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        zipField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ageField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        firstNameOrderText = new javax.swing.JTextField();
        phoneOrderText = new javax.swing.JTextField();
        emailOrderText = new javax.swing.JTextField();
        streetOrderText = new javax.swing.JTextField();
        street2OrderText = new javax.swing.JTextField();
        cityOrderText = new javax.swing.JTextField();
        zipOrderText = new javax.swing.JTextField();
        stateOrderCombo = new javax.swing.JComboBox();
        savannahCheck = new javax.swing.JCheckBox();
        trefoilCheck = new javax.swing.JCheckBox();
        dosidoCheck = new javax.swing.JCheckBox();
        samoaCheck = new javax.swing.JCheckBox();
        tagalongCheck = new javax.swing.JCheckBox();
        thinMintCheck = new javax.swing.JCheckBox();
        savannahText = new javax.swing.JTextField();
        trefoilText = new javax.swing.JTextField();
        dosidoText = new javax.swing.JTextField();
        samoaText = new javax.swing.JTextField();
        tagalongText = new javax.swing.JTextField();
        thinMintText = new javax.swing.JTextField();
        orderSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        totalBoxLabel = new javax.swing.JLabel();
        lastNameOrderText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        scoutFirstNameText = new javax.swing.JTextField();
        scoutLastNameText = new javax.swing.JTextField();
        paidCheck = new javax.swing.JCheckBox();
        pickedCheck = new javax.swing.JCheckBox();
        jTextField8 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jFrame3 = new javax.swing.JFrame();
        searchNameText = new javax.swing.JTextField();
        searchText = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultList = new javax.swing.JList();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jFrame1.setTitle("New Girl Scout...");
        jFrame1.setResizable(false);
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame1WindowClosing(evt);
            }
        });

        firstNameField.setText("First Name");
        firstNameField.setName("firstNameField"); // NOI18N
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        firstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusLost(evt);
            }
        });
        firstNameField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                firstNameFieldInputMethodTextChanged(evt);
            }
        });

        streetField.setText("Street Address");
        streetField.setToolTipText("");
        streetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetFieldActionPerformed(evt);
            }
        });
        streetField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                streetFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetFieldFocusLost(evt);
            }
        });

        aptField.setText("Street Address 2");
        aptField.setToolTipText("");
        aptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptFieldActionPerformed(evt);
            }
        });
        aptField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aptFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aptFieldFocusLost(evt);
            }
        });

        cityField.setText("City");
        cityField.setToolTipText("");
        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });
        cityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityFieldFocusLost(evt);
            }
        });

        zipField.setText("ZIP");
        zipField.setToolTipText("");
        zipField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipFieldActionPerformed(evt);
            }
        });
        zipField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                zipFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                zipFieldFocusLost(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lastNameField.setText("Last Name");
        lastNameField.setName("nameField"); // NOI18N
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });
        lastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusLost(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ageField.setText("Age");
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });
        ageField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFieldFocusLost(evt);
            }
        });

        jLabel3.setText("Insert New Girl Scout ");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(413, 413, 413)
                                .addComponent(jLabel1))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(aptField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jFrame1Layout.createSequentialGroup()
                                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3))))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aptField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        jFrame2.setTitle("Cookie Orders");
        jFrame2.setName("Cookie Order"); // NOI18N
        jFrame2.setResizable(false);
        jFrame2.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame2WindowClosing(evt);
            }
        });

        firstNameOrderText.setText("First Name");
        firstNameOrderText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameOrderTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameOrderTextFocusLost(evt);
            }
        });

        phoneOrderText.setText("Phone Number");
        phoneOrderText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneOrderTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneOrderTextFocusLost(evt);
            }
        });

        emailOrderText.setText("Email Address");
        emailOrderText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailOrderTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailOrderTextFocusLost(evt);
            }
        });

        streetOrderText.setText("Street Address");
        streetOrderText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                streetOrderTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetOrderTextFocusLost(evt);
            }
        });

        street2OrderText.setText("Street Address 2");
        street2OrderText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                street2OrderTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                street2OrderTextFocusLost(evt);
            }
        });

        cityOrderText.setText("City");
        cityOrderText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityOrderTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityOrderTextFocusLost(evt);
            }
        });

        zipOrderText.setText("ZIP");
        zipOrderText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                zipOrderTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                zipOrderTextFocusLost(evt);
            }
        });

        stateOrderCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY" }));
        stateOrderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateOrderComboActionPerformed(evt);
            }
        });

        savannahCheck.setText("Savannah Smiles");

        trefoilCheck.setText("Trefoils");

        dosidoCheck.setText("Do-Si-Dos");

        samoaCheck.setText("Samoas");

        tagalongCheck.setText("Tagalongs");

        thinMintCheck.setText("Thin Mints");

        savannahText.setText("0");
        savannahText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savannahTextActionPerformed(evt);
            }
        });
        savannahText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                savannahTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                savannahTextFocusLost(evt);
            }
        });

        trefoilText.setText("0");
        trefoilText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                trefoilTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                trefoilTextFocusLost(evt);
            }
        });

        dosidoText.setText("0");
        dosidoText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dosidoTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dosidoTextFocusLost(evt);
            }
        });

        samoaText.setText("0");
        samoaText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                samoaTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                samoaTextFocusLost(evt);
            }
        });

        tagalongText.setText("0");
        tagalongText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tagalongTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tagalongTextFocusLost(evt);
            }
        });

        thinMintText.setText("0");
        thinMintText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                thinMintTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                thinMintTextFocusLost(evt);
            }
        });

        orderSubmit.setText("Submit");
        orderSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSubmitActionPerformed(evt);
            }
        });

        jLabel4.setText("Cookie Type");

        jLabel5.setText("Number of Boxes");

        totalLabel.setText("Total: $0.00");

        totalBoxLabel.setText("Total Boxes: 0");

        lastNameOrderText.setText("Last Name");
        lastNameOrderText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameOrderTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameOrderTextFocusLost(evt);
            }
        });

        scoutFirstNameText.setText("Scout First Name");
        scoutFirstNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                scoutFirstNameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                scoutFirstNameTextFocusLost(evt);
            }
        });
        scoutFirstNameText.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                scoutFirstNameTextHierarchyChanged(evt);
            }
        });

        scoutLastNameText.setText("Scout Last Name");
        scoutLastNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                scoutLastNameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                scoutLastNameTextFocusLost(evt);
            }
        });

        paidCheck.setText("Paid");

        pickedCheck.setText("Picked Up");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(zipOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tagalongCheck)
                            .addComponent(dosidoCheck)
                            .addComponent(samoaCheck)
                            .addComponent(thinMintCheck)
                            .addGroup(jFrame2Layout.createSequentialGroup()
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameOrderText)
                                    .addComponent(phoneOrderText)
                                    .addComponent(emailOrderText)
                                    .addComponent(streetOrderText)
                                    .addComponent(street2OrderText)
                                    .addComponent(cityOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jFrame2Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(stateOrderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jFrame2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lastNameOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jFrame2Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(orderSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame2Layout.createSequentialGroup()
                                .addComponent(scoutFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scoutLastNameText)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickedCheck)
                            .addComponent(paidCheck))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame2Layout.createSequentialGroup()
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(savannahCheck)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(trefoilText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(savannahText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dosidoText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(samoaText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tagalongText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(thinMintText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(trefoilCheck))
                        .addGap(68, 68, 68)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalBoxLabel)
                            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                .addGap(2, 2, 2))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel8))
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scoutFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scoutLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phoneOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(streetOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(street2OrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateOrderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savannahText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savannahCheck))
                        .addGap(4, 4, 4)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trefoilCheck)
                            .addComponent(trefoilText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalBoxLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dosidoCheck)
                            .addComponent(dosidoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(samoaCheck)
                            .addComponent(samoaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paidCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tagalongCheck)
                            .addComponent(tagalongText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pickedCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thinMintCheck)
                            .addComponent(thinMintText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(orderSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField8.setText("jTextField8");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jFrame3.setTitle("Search For Orders");
        jFrame3.setName("Search For Orders"); // NOI18N
        jFrame3.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jFrame3WindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame3WindowClosing(evt);
            }
        });

        searchNameText.setText("Search...");
        searchNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameTextActionPerformed(evt);
            }
        });
        searchNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchNameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchNameTextFocusLost(evt);
            }
        });

        searchText.setText("Search");
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });

        searchResultList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(searchResultList);

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(searchText))
                    .addGroup(jFrame3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(searchNameText))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(searchText)
                .addContainerGap())
        );

        jPasswordField1.setText("jPasswordField1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Girl Scout Cookies");
        setName("Girl Scout Cookies"); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/girl-scouts-logo.gif"))); // NOI18N

        jMenu1.setText("File");

        jMenu5.setText("New...");

        jMenuItem1.setText("Girl Scout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Order");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenu1.add(jMenu5);

        jMenuItem3.setText("Search...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem4.setText("Girl Scout");
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Order");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jFrame1.setVisible(true);
        jFrame1.setSize(400,300);
        setVisible(true);
        setEnabled(false);
        jFrame1.setAlwaysOnTop(true);
        jLabel1.requestFocusInWindow();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void streetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetFieldActionPerformed

    private void streetFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetFieldFocusGained
        // TODO add your handling code here:
        if(streetField.getText().equals("Street Address"))
        streetField.setText(""); 
    }//GEN-LAST:event_streetFieldFocusGained

    private void streetFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetFieldFocusLost
        // TODO add your handling code here:
        if(streetField.getText().equals("")){
            streetField.setText("Street Address"); 
        }
    }//GEN-LAST:event_streetFieldFocusLost

    private void aptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aptFieldActionPerformed

    private void aptFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aptFieldFocusGained
        // TODO add your handling code here:
        if(aptField.getText().equals("Street Address 2"))
        aptField.setText("");
    }//GEN-LAST:event_aptFieldFocusGained

    private void aptFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aptFieldFocusLost
        // TODO add your handling code here:
        if(aptField.getText().equals("")){
            aptField.setText("Street Address 2");
        }
    }//GEN-LAST:event_aptFieldFocusLost

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cityFieldActionPerformed

    private void cityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFieldFocusGained
        // TODO add your handling code here:
        if(cityField.getText().equals("City"))
        cityField.setText("");
    }//GEN-LAST:event_cityFieldFocusGained

    private void cityFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFieldFocusLost
        // TODO add your handling code here:
        if(cityField.getText().equals("")){
            cityField.setText("City");
        }
    }//GEN-LAST:event_cityFieldFocusLost

    private void firstNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusGained
        // TODO add your handling code here:
        if(firstNameField.getText().equals("First Name"))
        firstNameField.setText(""); 
    }//GEN-LAST:event_firstNameFieldFocusGained

    private void zipFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipFieldActionPerformed

    private void zipFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipFieldFocusGained
        // TODO add your handling code here:
        if(zipField.getText().equals("ZIP"))
        zipField.setText("");
    }//GEN-LAST:event_zipFieldFocusGained

    private void zipFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipFieldFocusLost
        // TODO add your handling code here:
        if(zipField.getText().equals("")){
            zipField.setText("ZIP");
        }
    }//GEN-LAST:event_zipFieldFocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void firstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusLost
        // TODO add your handling code here:
        if(firstNameField.getText().equals("")){
            firstNameField.setText("First Name"); 
        }
    }//GEN-LAST:event_firstNameFieldFocusLost

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void lastNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusGained
        // TODO add your handling code here:
        if(lastNameField.getText().equals("Last Name"))
            lastNameField.setText("");
    }//GEN-LAST:event_lastNameFieldFocusGained

    private void lastNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusLost
        // TODO add your handling code here:
        if(lastNameField.getText().equals(""))
            lastNameField.setText("Last Name");
    }//GEN-LAST:event_lastNameFieldFocusLost

    private void jFrame1WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowClosing
        // TODO add your handling code here:
        requestFocusInWindow();
        setEnabled(true);
            firstNameField.setText("First Name");
            lastNameField.setText("Last Name");
            ageField.setText("Age");
            streetField.setText("Street Address");
            aptField.setText("Street Address 2");
            cityField.setText("City");
            zipField.setText("ZIP");
        
    }//GEN-LAST:event_jFrame1WindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        //int checked = 0;
        try{
            String name = firstNameField.getText() + " " + lastNameField.getText();
            int age = Integer.parseInt(ageField.getText());
            String address = streetField.getText() + ", " + cityField.getText() + ", IN " + zipField.getText();
            SQLiteJDBC jdbc = new SQLiteJDBC();
            jdbc.insertScout(name, address, age);
//            Integer.parseInt(lastNameField.getText());
//            Integer.parseInt(phoneField.getText());
            jFrame1.dispose();
            setEnabled(true);
            requestFocusInWindow();
            toFront();
            
            firstNameField.setText("First Name");
            lastNameField.setText("Last Name");
            ageField.setText("Age");
            streetField.setText("Street Address");
            aptField.setText("Street Address 2");
            cityField.setText("City");
            zipField.setText("ZIP");
        }
        catch(Exception e){
            JPanel error = new JPanel();
            JOptionPane.showMessageDialog(error, e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
            //checked = 0;
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jFrame2.setVisible(true);
        jFrame2.setSize(420,620);
        setVisible(true);
        setEnabled(false);
        jFrame2.setAlwaysOnTop(true);
        jFrame2.requestFocusInWindow();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void firstNameFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_firstNameFieldInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldInputMethodTextChanged

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void ageFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusGained
        // TODO add your handling code here:
         if(ageField.getText().equals("Age")){
            ageField.setText("");}
    }//GEN-LAST:event_ageFieldFocusGained

    private void ageFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusLost
        // TODO add your handling code here:
        if(ageField.getText().equals("")){
           ageField.setText("Age");}
    }//GEN-LAST:event_ageFieldFocusLost

    private void searchNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchNameTextFocusLost
        // TODO add your handling code here:
        if(searchNameText.getText().equals("")){
            searchNameText.setText("Search...");
        }
    }//GEN-LAST:event_searchNameTextFocusLost

    private void searchNameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchNameTextFocusGained
        // TODO add your handling code here:
        if(searchNameText.getText().equals("Search...")){
            searchNameText.setText("");
        }
    }//GEN-LAST:event_searchNameTextFocusGained

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jFrame3.setVisible(true);
        setVisible(true);
        setEnabled(false);
        jFrame3.pack();
        jFrame3.setAlwaysOnTop(true);
        jFrame3.requestFocusInWindow();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jFrame3WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame3WindowClosing
        // TODO add your handling code here:
        requestFocusInWindow();
        setEnabled(true);
        listModel.clear();
        searchNameText.setText("");
        
    }//GEN-LAST:event_jFrame3WindowClosing

    private void jFrame2WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame2WindowClosing
        // TODO add your handling code here:
        requestFocusInWindow();
        setEnabled(true);
        
        scoutFirstNameText.setText("Scout First Name");
            scoutLastNameText.setText("Scout Last Name");
            firstNameOrderText.setText("First Name");
            lastNameOrderText.setText("Last Name");
            phoneOrderText.setText("Phone Number");
            emailOrderText.setText("Email Address");
            streetOrderText.setText("Street Address");
            street2OrderText.setText("Street Address 2");
            cityOrderText.setText("City");
            zipOrderText.setText("Zip");
            savannahText.setText("0");
            trefoilText.setText("0");
            dosidoText.setText("0");
            samoaText.setText("0");
            tagalongText.setText("0");
            thinMintText.setText("0");
            paidCheck.setSelected(false);
            pickedCheck.setSelected(false);
    }//GEN-LAST:event_jFrame2WindowClosing

    private void lastNameOrderTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameOrderTextFocusLost
        // TODO add your handling code here:
        if(lastNameOrderText.getText().equals(""))
        lastNameOrderText.setText("Last Name");
    }//GEN-LAST:event_lastNameOrderTextFocusLost

    private void lastNameOrderTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameOrderTextFocusGained
        // TODO add your handling code here:
        if (lastNameOrderText.getText().equals("Last Name"))
        lastNameOrderText.setText("");
    }//GEN-LAST:event_lastNameOrderTextFocusGained

    private void thinMintTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_thinMintTextFocusLost
        // TODO add your handling code here:
        if(thinMintText.getText().equals("")){
            thinMintText.setText("0");
        }
        else{
            totals(thinMintText.getText(), 5);
            thinMintCheck.setSelected(true);
            if(thinMintText.getText().equals("0")){
                thinMintCheck.setSelected(false);
            }
        }
    }//GEN-LAST:event_thinMintTextFocusLost

    private void thinMintTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_thinMintTextFocusGained
        // TODO add your handling code here:
        if(thinMintText.getText().equals("0")){
            thinMintText.setText("");
            previousBox[5]=0;
        }
        else{
            try{
                previousBox[5] = Integer.parseInt(thinMintText.getText());
            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_thinMintTextFocusGained

    private void tagalongTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tagalongTextFocusLost
        // TODO add your handling code here:
        if(tagalongText.getText().equals("")){
            tagalongText.setText("0");
        }
        else{
            totals(tagalongText.getText(), 4);
            tagalongCheck.setSelected(true);
            if(tagalongText.getText().equals("0")){
                tagalongCheck.setSelected(false);
            }
        }
    }//GEN-LAST:event_tagalongTextFocusLost

    private void tagalongTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tagalongTextFocusGained
        // TODO add your handling code here:
        if(tagalongText.getText().equals("0")){
            tagalongText.setText("");
            tagalongCheck.setSelected(false);
            previousBox[4]=0;
        }
        else{
            try{
                previousBox[4] = Integer.parseInt(tagalongText.getText());
            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_tagalongTextFocusGained

    private void samoaTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_samoaTextFocusLost
        // TODO add your handling code here:
        if(samoaText.getText().equals("")){
            samoaText.setText("0");
        }
        else{
            totals(samoaText.getText(), 3);
            samoaCheck.setSelected(true);
            if(samoaText.getText().equals("0")){
                samoaCheck.setSelected(false);
            }
        }
    }//GEN-LAST:event_samoaTextFocusLost

    private void samoaTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_samoaTextFocusGained
        // TODO add your handling code here:
        if(samoaText.getText().equals("0")){
            samoaText.setText("");
            previousBox[3]=0;
            samoaCheck.setSelected(false);
        }
        else{
            try{
                previousBox[3] = Integer.parseInt(samoaText.getText());
            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_samoaTextFocusGained

    private void dosidoTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dosidoTextFocusLost
        // TODO add your handling code here:
        if(dosidoText.getText().equals("")){
            dosidoText.setText("0");
        }
        else{
            totals(dosidoText.getText(), 2);
            dosidoCheck.setSelected(true);
            if(dosidoText.getText().equals("0")){
                dosidoCheck.setSelected(false);
            }
        }
    }//GEN-LAST:event_dosidoTextFocusLost

    private void dosidoTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dosidoTextFocusGained
        // TODO add your handling code here:
        if(dosidoText.getText().equals("0")){
            dosidoText.setText("");
            previousBox[2]=0;
            dosidoCheck.setSelected(false);
        }
        else{
            try{
                previousBox[2] = Integer.parseInt(dosidoText.getText());
            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_dosidoTextFocusGained

    private void trefoilTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_trefoilTextFocusLost
        // TODO add your handling code here:
        if(trefoilText.getText().equals("")){
            trefoilText.setText("0");
        }
        else{
            totals(trefoilText.getText(), 1);
            trefoilCheck.setSelected(true);
            if(trefoilText.getText().equals("0")){
                trefoilCheck.setSelected(false);
            }
        }
    }//GEN-LAST:event_trefoilTextFocusLost

    private void trefoilTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_trefoilTextFocusGained
        // TODO add your handling code here:
        if(trefoilText.getText().equals("0")){
            trefoilText.setText("");
            previousBox[1]=0;
            trefoilCheck.setSelected(false);
        }
        else{
            try{
                previousBox[1] = Integer.parseInt(trefoilText.getText());
            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_trefoilTextFocusGained

    private void savannahTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_savannahTextFocusLost
        // TODO add your handling code here:
        if(savannahText.getText().equals("")){
            savannahText.setText("0");
        }
        else{
            totals(savannahText.getText(), 0);
            savannahCheck.setSelected(true);
            if(savannahText.getText().equals("0")){
                savannahCheck.setSelected(false);
            }
        }
    }//GEN-LAST:event_savannahTextFocusLost

    private void savannahTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_savannahTextFocusGained
        // TODO add your handling code here:

        if(savannahText.getText().equals("0")){
            savannahText.setText("");
            previousBox[0]=0;
            savannahCheck.setSelected(false);
        }
        else{
            try{
                previousBox[0] = Integer.parseInt(savannahText.getText());
            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_savannahTextFocusGained

    private void savannahTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savannahTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savannahTextActionPerformed

    private void zipOrderTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipOrderTextFocusLost
        // TODO add your handling code here:
        if(zipOrderText.getText().equals(""))
        zipOrderText.setText("ZIP");
    }//GEN-LAST:event_zipOrderTextFocusLost

    private void zipOrderTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipOrderTextFocusGained
        // TODO add your handling code here:
        if(zipOrderText.getText().equals("ZIP"))
        zipOrderText.setText("");
    }//GEN-LAST:event_zipOrderTextFocusGained

    private void cityOrderTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityOrderTextFocusLost
        // TODO add your handling code here:
        if(cityOrderText.getText().equals(""))
        cityOrderText.setText("City");
    }//GEN-LAST:event_cityOrderTextFocusLost

    private void cityOrderTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityOrderTextFocusGained
        // TODO add your handling code here:
        if(cityOrderText.getText().equals("City"))
        cityOrderText.setText("");
    }//GEN-LAST:event_cityOrderTextFocusGained

    private void street2OrderTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_street2OrderTextFocusLost
        // TODO add your handling code here:
        if(street2OrderText.getText().equals(""))
        street2OrderText.setText("Street Address 2");
    }//GEN-LAST:event_street2OrderTextFocusLost

    private void street2OrderTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_street2OrderTextFocusGained
        // TODO add your handling code here:
        if(street2OrderText.getText().equals("Street Address 2"))
        street2OrderText.setText("");
    }//GEN-LAST:event_street2OrderTextFocusGained

    private void streetOrderTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetOrderTextFocusLost
        // TODO add your handling code here:
        if(streetOrderText.getText().equals(""))
        streetOrderText.setText("Street Address");
    }//GEN-LAST:event_streetOrderTextFocusLost

    private void streetOrderTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetOrderTextFocusGained
        // TODO add your handling code here:
        if(streetOrderText.getText().equals("Street Address"))
        streetOrderText.setText("");
    }//GEN-LAST:event_streetOrderTextFocusGained

    private void emailOrderTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailOrderTextFocusLost
        // TODO add your handling code here:
        if(emailOrderText.getText().equals(""))
        emailOrderText.setText("Email Address");
    }//GEN-LAST:event_emailOrderTextFocusLost

    private void emailOrderTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailOrderTextFocusGained
        // TODO add your handling code here:
        if(emailOrderText.getText().equals("Email Address"))
        emailOrderText.setText("");
    }//GEN-LAST:event_emailOrderTextFocusGained

    private void phoneOrderTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneOrderTextFocusLost
        // TODO add your handling code here:
        if(phoneOrderText.getText().equals(""))
        phoneOrderText.setText("Phone Number");
    }//GEN-LAST:event_phoneOrderTextFocusLost

    private void phoneOrderTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneOrderTextFocusGained
        // TODO add your handling code here:
        if(phoneOrderText.getText().equals("Phone Number"))
        phoneOrderText.setText("");
    }//GEN-LAST:event_phoneOrderTextFocusGained

    private void firstNameOrderTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameOrderTextFocusLost
        // TODO add your handling code here:
        if(firstNameOrderText.getText().equals(""))
        firstNameOrderText.setText("First Name");
    }//GEN-LAST:event_firstNameOrderTextFocusLost

    private void firstNameOrderTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameOrderTextFocusGained
        // TODO add your handling code here:
        if (firstNameOrderText.getText().equals("First Name"))
        firstNameOrderText.setText("");
    }//GEN-LAST:event_firstNameOrderTextFocusGained

    private void orderSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSubmitActionPerformed
        // TODO add your handling code here:
        
        try{
            String cust_name = firstNameOrderText.getText() + " " + lastNameOrderText.getText();
            String cust_address = streetOrderText.getText() + ", " + cityOrderText.getText() + ", " + "IN " + zipOrderText.getText();
            int phone = Integer.parseInt(phoneOrderText.getText());
            String email = emailOrderText.getText();
            
            SQLiteJDBC jdbc = new SQLiteJDBC();
            jdbc.insertCustomer(cust_name, cust_address, phone, email);
            
            boolean paid = paidCheck.isSelected();
            boolean pickedup = pickedCheck.isSelected();
            String scout_name = scoutFirstNameText.getText() + " " + scoutLastNameText.getText();
            int amount = 0;
            
            if (samoaCheck.isSelected()) {
                amount = Integer.parseInt(samoaText.getText());
                jdbc.insertOrder(cust_name, scout_name, "Samoas", amount, paid, pickedup);
            }
            
            if (savannahCheck.isSelected()) {
                amount = Integer.parseInt(savannahText.getText());
                jdbc.insertOrder(cust_name, scout_name, "Savannah Smiles", amount, paid, pickedup);
            }
            
            if (trefoilCheck.isSelected()) {
                amount = Integer.parseInt(trefoilText.getText());
                jdbc.insertOrder(cust_name, scout_name, "Trefoils", amount, paid, pickedup);
            }
            
            if (tagalongCheck.isSelected()) {
                amount = Integer.parseInt(tagalongText.getText());
                jdbc.insertOrder(cust_name, scout_name, "Tagalongs", amount, paid, pickedup);
            }
            
            if (thinMintCheck.isSelected()) {
                amount = Integer.parseInt(thinMintText.getText());
                jdbc.insertOrder(cust_name, scout_name, "Thin Mints", amount, paid, pickedup);
            }
            
            if (dosidoCheck.isSelected()) {
                amount = Integer.parseInt(dosidoText.getText());
                jdbc.insertOrder(cust_name, scout_name, "Do-Si-Dos", amount, paid, pickedup);
            }
            
            scoutFirstNameText.setText("Scout First Name");
            scoutLastNameText.setText("Scout Last Name");
            firstNameOrderText.setText("First Name");
            lastNameOrderText.setText("Last Name");
            phoneOrderText.setText("Phone Number");
            emailOrderText.setText("Email Address");
            streetOrderText.setText("Street Address");
            street2OrderText.setText("Street Address 2");
            cityOrderText.setText("City");
            zipOrderText.setText("Zip");
            savannahText.setText("0");
            trefoilText.setText("0");
            dosidoText.setText("0");
            samoaText.setText("0");
            tagalongText.setText("0");
            thinMintText.setText("0");
            paidCheck.setSelected(false);
            pickedCheck.setSelected(false);
            
            
            
            jFrame2.dispose();
            setEnabled(true);
            requestFocusInWindow();
            toFront();
            
        }
        catch (Exception e){
            JPanel error = new JPanel();
            JOptionPane.showMessageDialog(error, e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_orderSubmitActionPerformed

    private void scoutFirstNameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scoutFirstNameTextFocusGained
        // TODO add your handling code here:
        if(scoutFirstNameText.getText().equals("Scout First Name"))
        scoutFirstNameText.setText("");
    }//GEN-LAST:event_scoutFirstNameTextFocusGained

    private void scoutFirstNameTextHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_scoutFirstNameTextHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_scoutFirstNameTextHierarchyChanged

    private void scoutFirstNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scoutFirstNameTextFocusLost
        // TODO add your handling code here:
        if(scoutFirstNameText.getText().equals(""))
        scoutFirstNameText.setText("Scout First Name");
    }//GEN-LAST:event_scoutFirstNameTextFocusLost

    private void scoutLastNameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scoutLastNameTextFocusGained
        // TODO add your handling code here:
        if(scoutLastNameText.getText().equals("Scout's Last Name"))
        scoutLastNameText.setText("");
    }//GEN-LAST:event_scoutLastNameTextFocusGained

    private void scoutLastNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scoutLastNameTextFocusLost
        // TODO add your handling code here:
        if(scoutLastNameText.getText().equals(""))
        scoutLastNameText.setText("Scout Last Name");
    }//GEN-LAST:event_scoutLastNameTextFocusLost

    private void searchNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameTextActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_searchNameTextActionPerformed

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
        //listModel.addElement("HI");
        try {
            String searchName = searchNameText.getText();
            SQLiteJDBC jdbc = new SQLiteJDBC();
            Vector<String> searchResult = jdbc.findScout(searchName);
            
            for (int i = 0; i < searchResult.size(); i++) {
                
                listModel.addElement(searchResult.get(i));
            }
                
        }
        catch (Exception e) {
            JPanel error = new JPanel();
            JOptionPane.showMessageDialog(error, e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchTextActionPerformed

    private void jFrame3WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame3WindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFrame3WindowActivated

    private void stateOrderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateOrderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateOrderComboActionPerformed
    private void totals(String s, int whichBox){
        int tempBoxes = 0;
        try{
            tempBoxes = Integer.parseInt(s);
            
        }
        catch(Exception e){
            System.out.println("Not a string");
        }
        totalBoxes += (tempBoxes-previousBox[whichBox]);
        total = totalBoxes * boxPrice;
        totalBoxLabel.setText(totalBoxString+totalBoxes);
        String tempTotal = String.format("%,6.2f",total);
        totalLabel.setText(totalString+tempTotal);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GS_GUI().setVisible(true);
                
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JTextField aptField;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField cityOrderText;
    private javax.swing.JCheckBox dosidoCheck;
    private javax.swing.JTextField dosidoText;
    private javax.swing.JTextField emailOrderText;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField firstNameOrderText;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField lastNameOrderText;
    private javax.swing.JButton orderSubmit;
    private javax.swing.JCheckBox paidCheck;
    private javax.swing.JTextField phoneOrderText;
    private javax.swing.JCheckBox pickedCheck;
    private javax.swing.JCheckBox samoaCheck;
    private javax.swing.JTextField samoaText;
    private javax.swing.JCheckBox savannahCheck;
    private javax.swing.JTextField savannahText;
    private javax.swing.JTextField scoutFirstNameText;
    private javax.swing.JTextField scoutLastNameText;
    private javax.swing.JTextField searchNameText;
    private javax.swing.JList searchResultList;
    private javax.swing.JButton searchText;
    private javax.swing.JComboBox stateOrderCombo;
    private javax.swing.JTextField street2OrderText;
    private javax.swing.JTextField streetField;
    private javax.swing.JTextField streetOrderText;
    private javax.swing.JCheckBox tagalongCheck;
    private javax.swing.JTextField tagalongText;
    private javax.swing.JCheckBox thinMintCheck;
    private javax.swing.JTextField thinMintText;
    private javax.swing.JLabel totalBoxLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JCheckBox trefoilCheck;
    private javax.swing.JTextField trefoilText;
    private javax.swing.JTextField zipField;
    private javax.swing.JTextField zipOrderText;
    // End of variables declaration//GEN-END:variables
}
